resources:
  - name: app1
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master

  - name: myDockerImg
    type: image
    imageName: demo/app
    configuration:
      integrationName: artDocker
      autoPull: false
    initialVersion:
      imageTag: latest

  # - name: myState
  #   type: state
  #
  # - name: p2pWebhook
  #   type: webhook
  #   configuration:
  #     integrationName: intWebhook
  #   initialVersion:
  #     payload: "foo=bar"
  #
  # - name: extWebhook
  #   type: webhook
  #   configuration:
  #     integrationName: myExtWebhook
  #   initialVersion:
  #     payload: "foo=bar"

pipelines:

  - name: test_pipeline
    steps:
      - name: build
        type: bash
        configuration:
          affinityGroup: build
          #nodePool: kermit_centos_pool        requires:
          resources:
            - app1
        execution:
          onExecute:
            - printenv
            - pushd $res_app1_resourcePath
            - docker build -t app1:$STEP_ID .
            - write_output myDockerImg "imageTag="$STEP_ID
            - add_run_variable imageName=$res_myDockerImg_imageName
            - add_run_variable imageTag=$STEP_ID
        outputResources:
          - myDockerImg

      - name: test
        type: bash
        configuration:
          affinityGroup: build
          #nodePool: kermit_centos_pool
        triggeredBy:
          resources:
            - myDockerImg
        execution:
          onExecute:
            - printenv
            - docker run --name "test_app" app1:$res_myDockerImg_imageTag bash -c "pwd"
            - docker rm -fv "test_app"
            - echo $res_myDockerImg_imageTag

      - name: parallel_1
        type: bash
        triggeredBy:
          steps:
            - test
        execution:
          onExecute:
            - printenv
            - echo $imageTag


      - name: parallel_2
        type: bash
        triggeredBy:
          steps:
            - test
        execution:
          onExecute:
            - printenv

      - name: parallel_3
        type: bash
        triggeredBy:
          steps:
            - test
        execution:
          onExecute:
            - printenv

      - name: push
        type: bash
        triggeredBy:
          steps:
            - parallel_2
            - parallel_1
            - parallel_3
        requires:
          integrations:
            - artDocker
        execution:
          onExecute:
            - docker login -u $int_artDocker_username -p $int_artDocker_password $int_artDocker_url
            - artIp=$(echo $int_artDocker_url | awk -F[/:] '{print $4}')
            - artPort=$(echo $int_artDocker_url | awk -F[/:] '{print $5}')
            - echo "$artIp:$artPort"
            - docker tag app:$imageTag $artIp:$artPort/$imageName:$imageTag
            - docker push $artIp:$artPort/$imageName:$imageTag



  - name: second_test_pipeline
    steps:
      - name: first_step
        type: bash
        requires:
          resources:
            - app1
        execution:
          onExecute:
            - printenv


  #
  #
  # - name: ci_pipeline
  #   steps:
  #     - name: build
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       triggeredBy:
  #         resources:
  #           - app
  #       execution:
  #         onExecute:
  #           - pushd $res_app_resourcePath
  #           - docker build -t app:latest .
  #
  #     - name: test
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       triggeredBy:
  #         steps:
  #           - build
  #       execution:
  #         onExecute:
  #           - docker run --name "test_app" app:latest bash -c "pwd"
  #           - docker rm -fv "test_app"
  #
  #     - name: push
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       requires:
  #         integrations:
  #           - art
  #       triggeredBy:
  #         steps:
  #           - test
  #       execution:
  #         onExecute:
  #           - docker login -u $int_art_username -p $int_art_password $int_art_url
  #           - artIp=$(echo $int_art_url | awk -F[/:] '{print $4}')
  #           - artPort=$(echo $int_art_url | awk -F[/:] '{print $5}')
  #           - echo "$artIp:$artPort"
  #           - docker tag app:latest $artIp:$artPort/demo/app:$STEP_ID
  #           - docker push $artIp:$artPort/demo/app:$STEP_ID
  #
  #     - name: job2
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #
  #       triggeredBy:
  #         steps:
  #           - build
  #       execution:
  #         onExecute:
  #           - echo "job2...."
