resources:
  - name: app1
    type: gitRepo
    repoPath: manishas/app
    configuration:
      integrationName: manishas_github
      branches:
        only: master
    initialVersion:
      sha: master

  - name: myState
    type: state

  - name: p2pWebhook
    type: webhook
    configuration:
      integrationName: intWebhook
    initialVersion:
      payload: "foo=bar"

  - name: extWebhook
    type: webhook
    configuration:
      integrationName: myExtWebhook
    initialVersion:
      payload: "foo=bar"

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: bash
        configuration:
          affinityGroup: build
        setup:
          environmentVariables:
            normal:
              myFirstName: Manisha
              myLastName: Sahasrabudhe
            encrypted:
              myMiddleName: P0MA0FvspdmtybGshqsaGHwisg+oSu8DcLA7biLiZGhoSgrKpua4yZHqy5dWPakhUXZrvqd/TQGGR6TvIFqKcPrkG1aCzhVIScDL6ZuWGgvoUKqeAyppnAnRMh17t2hCmpvgJrd9+hmeqRprGL+CBsDnzpjQ4plIogt4tPpJq8CnDqMVTzKvVuafJhPen7fBDCJ/SuK1co7cdDoayziNI8ARFvWVSBt2OEE73qtsOK66F+Jm51R/HKJplCSl1/CVbJepVXf3uFoC6WOBygv7fpSxaPSrV60JIt02CYfstVlWFk48oKcmaJcldRbMmlhBHiGjdX9VduGUF7QTQNDE8w==
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16all
                tag: master
        requires:
          resources:
            - app1
          integrations:
            - art
        execution:
          onExecute:
            - echo $myFirstName
            - echo $myLastName
            - echo $myMiddleName
            - printenv


      - name: test_func_next
        type: bash
        configuration:
          affinityGroup: build
        triggeredBy:
          steps:
            - test_func
        execution:
          onExecute:
            - printenv


      - name: parallel_1
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv
            - echo $imageTag


      - name: parallel_2
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: parallel_3
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: final_step
        type: bash
        triggeredBy:
          steps:
            - parallel_2
            - parallel_1
            - parallel_3
        outputResources:
          - myState
        execution:
          onExecute:
            - printenv



  - name: second_test_pipeline
    steps:
      - name: first_step
        type: bash
        requires:
          resources:
            - app1
            - myState
        execution:
          onExecute:
            - printenv


  #
  #
  # - name: ci_pipeline
  #   steps:
  #     - name: build
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       triggeredBy:
  #         resources:
  #           - app
  #       execution:
  #         onExecute:
  #           - pushd $res_app_resourcePath
  #           - docker build -t app:latest .
  #
  #     - name: test
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       triggeredBy:
  #         steps:
  #           - build
  #       execution:
  #         onExecute:
  #           - docker run --name "test_app" app:latest bash -c "pwd"
  #           - docker rm -fv "test_app"
  #
  #     - name: push
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #       requires:
  #         integrations:
  #           - art
  #       triggeredBy:
  #         steps:
  #           - test
  #       execution:
  #         onExecute:
  #           - docker login -u $int_art_username -p $int_art_password $int_art_url
  #           - artIp=$(echo $int_art_url | awk -F[/:] '{print $4}')
  #           - artPort=$(echo $int_art_url | awk -F[/:] '{print $5}')
  #           - echo "$artIp:$artPort"
  #           - docker tag app:latest $artIp:$artPort/demo/app:$STEP_ID
  #           - docker push $artIp:$artPort/demo/app:$STEP_ID
  #
  #     - name: job2
  #       type: bash
  #       setup:
  #         runtime:
  #           type: image
  #           image:
  #            custom:
  #              name: drydock/u16all
  #              tag: master
  #
  #       triggeredBy:
  #         steps:
  #           - build
  #       execution:
  #         onExecute:
  #           - echo "job2...."
